######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/educenter/site/"
title = "LEL | Lars-Erik Larsson gymnasiet"
theme = "educenter-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/Stockholm"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = ["Fr", "en"] 
# example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
defaultContentLanguage = "sv"
languageCode = "sv"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info 
address = "Bredgatan 13, 222 21 Lund "
mobile = "046-378 13 00"
email = " info@lel.nu"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "55.70775390768936" 
map_longitude = "13.192557526190381"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://sv-se.facebook.com/lelilund/"


[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/larseriklarssongymnasiet/"

[[params.social]]
title = "tik-tok"
icon = "ti-tumblr" # themify icon : https://themify.me/themify-icons
link = "https://www.tiktok.com/discover/lars-erik-larsson-gymnasiet"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://se.linkedin.com/school/lars-erik-larsson-gymnasiet/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[Languages.en.params]
home = "Hem"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Vår skola"
url = "about/"
weight = 1

 [[Languages.en.menu.main]]
  parent = "Vår skola"
  name = "Om oss"
  url = "about/"
  weight = 2

[[Languages.en.menu.main]]
parent = "Vår skola"
name = "Läsårstider"
url = "skolinfo/"
weight = 3

[[Languages.en.menu.main]]
parent = "Vår skola"
name = "Elevrådet"
url = "elevrad/"
weight = 4

[[Languages.en.menu.main]]
parent = "Vår skola"
name = "Utskott"
url = "utskott/"
weight = 5

[[Languages.en.menu.main]]
parent = "Vår skola"
name = "Internationalisering"
url = "international/"
weight = 6


[[Languages.en.menu.main]]
name = "Program"
url = "course/"
weight = 2

[[Languages.en.menu.main]]
parent = "Program"
name = "Naturprogrammet"
url = "course/natur"
weight = 1

[[Languages.en.menu.main]]
parent = "Program"
name = "Samhällsprogrammet"
url = "course/samhälle"
weight = 2

[[Languages.en.menu.main]]
parent="Program"
name = "NASA"
url = "course/nasa"
weight = 3

[[Languages.en.menu.main]]
parent = "Program"
name = "Musikprofilen"
url = "musikprofilen"
weight = 4

[[Languages.en.menu.main]]
name = "Evenemang"
url = "event/"
weight = 4

#[[Languages.en.menu.main]]
#name = "Händelser"
#url = "blog/"
#weight = 5‹

[[Languages.en.menu.main]]
weight = 3
name = "Ansökan"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Ansökan"
  name = "Sök till LEL"
  url = "apply/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Ansökan"
  name = "Skugga en elev"
  url = "skugga"
  weight = 3

  [[Languages.en.menu.main]]
  parent = "Ansökan"
  name = "Inträdesprov"
  url = "prov/"
  weight = 2

  
[[Languages.en.menu.main]]
name = "Kontakt"
url = "kontakt/"
weight = 6

  [[Languages.en.menu.main]]
  parent = "Kontakt"
  name = "Personal"
  url = "teacher/"

   [[Languages.en.menu.main]]
  parent = "Kontakt"
  name = "Kontaktformulär"
  url = "kontakt/"

[[Languages.en.menu.main]]
name = "Nyheter"
url = "blog/"
weight = 5

# footer menu

[[Languages.en.menu.footer]]
name = "nyheter"
url = "notice/"

[[Languages.en.menu.footer]]
name = "händelser"
url = "event/"

[[Languages.en.menu.footer]]
name = "Program"
url = "courses/"

################################### Swedish language #####################################
[Languages.sv]
languageName = "Sv"
languageCode = "sv-SE"
contentDir = "content/swedish"
weight = 1

[Languages.sv.params]
home = "Hem"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### Swedish navigation ####################

# main menu
[[Languages.sv.menu.main]]
name = "skola"
url = "about/"
weight = 1

 [[Languages.sv.menu.main]]
  parent = "skola"
  name = "Om oss"
  url = "about/"
  weight = 2

  [[Languages.sv.menu.main]]
  parent = "skola"
  name = "Läsårstider"
  url = "skolinfo/"
  weight = 3

  [[Languages.sv.menu.main]]
  parent = "skola"
  name = "Elevkåren"
  url = "elevrad/"
  weight = 4

  [[Languages.sv.menu.main]]
  parent = "skola"
  name = "Utskott"
  url = "utskott/"
  weight = 5

  [[Languages.sv.menu.main]]
  parent = "skola"
  name = "Internationalisering"
  url = "international/"
  weight = 6


[[Languages.sv.menu.main]]
name = "Program"
url = "course/"
weight = 2

  [[Languages.sv.menu.main]]
  parent = "Program"
  name = "Naturprogrammet"
  url = "course/natur"
  weight = 1

  [[Languages.sv.menu.main]]
  parent = "Program"
  name = "Samhällsprogrammet"
  url = "course/samhälle"
  weight = 2

  [[Languages.sv.menu.main]]
  parent="Program"
  name = "Natur-samhälle"
  url = "course/nasa"
  weight = 3

  [[Languages.sv.menu.main]]
  parent = "Program"
  name = "Musikprofilen"
  url = "musikprofilen"
  weight = 4

[[Languages.sv.menu.main]]
name = "Evenemang"
url = "event/"
weight = 4

#[[Languages.sv.menu.main]]
#name = "Händelser"
#url = "blog/"
#weight = 5‹

[[Languages.sv.menu.main]]
weight = 3
name = "Ansökan"
hasChildren = true

  [[Languages.sv.menu.main]]
  parent = "Ansökan"
  name = "Sök till LEL"
  url = "apply/"
  weight = 1

  [[Languages.sv.menu.main]]
  parent = "Ansökan"
  name = "Skugga en elev"
  url = "skugga"
  weight = 3

  [[Languages.sv.menu.main]]
  parent = "Ansökan"
  name = "Inträdesprov"
  url = "prov/"
  weight = 2

  
[[Languages.sv.menu.main]]
name = "Kontakt"
url = "kontakt/"
weight = 6

  [[Languages.sv.menu.main]]
  parent = "Kontakt"
  name = "Personal"
  url = "teacher/"

   [[Languages.sv.menu.main]]
  parent = "Kontakt"
  name = "Kontaktformulär"
  url = "kontakt/"

[[Languages.sv.menu.main]]
name = "Nyheter"
url = "blog/"
weight = 5

 [[Languages.sv.menu.main]]
  parent = "Nyheter"
  name = "Artiklar"
  url = "blog"
  weight = 3

 [[Languages.sv.menu.main]]
  parent = "Nyheter"
  name = "Händelser"
  url = "notice"
  weight = 3


# footer menu

[[Languages.sv.menu.footer]]
name = "Nyheter"
url = "blog/"

[[Languages.sv.menu.footer]]
name = "Evenemang"
url = "event/"

[[Languages.sv.menu.footer]]
name = "Program"
url = "courses/"

[[Languages.sv.menu.footer]]
name = "Recensioner"
url = "recensioner/"
